### ISSUE TITLE
Can't completely logout

### ISSUE THREAD

**Issue by Vodolazkyi** [shyambhat/InstagramKit#252] opened 2016-09-08 20:42 UTC
After InstagramEngine.sharedEngine().logout() sometimes not asking for a login and password. (if you logout and try login it's good, but when logout, kill the app and its not asking to enter password)

```
    NSURLCache.sharedURLCache().removeAllCachedResponses()
    NSURLCache.sharedURLCache().diskCapacity = 0
    NSURLCache.sharedURLCache().memoryCapacity = 0
```

Also not help.

**Comment by shyambhat** [comment] 2018-06-03 22:04
I can't reproduce this problem in iOS 11. I'm closing this issue since it's old. If the problem persists, please feel free to reopen.

**Closed by shyambhat** 2018-06-03 22:04 UTC
